name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Apply black formatting
        run: |
          black --extend-exclude "stubs|external|coreblocks|transactron|amaranth-stubs" .
      - name: Commit formatted code
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -am "Apply black formatting"
            git push
          fi
      - name: Check formatting with black
        run: |
          black --extend-exclude "stubs|external|coreblocks|transactron|amaranth-stubs" --check .
      - name: Run pytest
        run: |
          pytest -n auto
